# Generated by Django 4.0.2 on 2022-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_club_country_alter_club_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
