# Generated by Django 4.0.2 on 2022-02-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_club_country_alter_club_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'club', 'verbose_name_plural': 'clubs'},
        ),
        migrations.AlterModelOptions(
            name='kudos',
            options={'verbose_name': 'kudos', 'verbose_name_plural': 'kudos'},
        ),
    ]
